### ISSUE TITLE
test_import_patched_defaults fails with pyopenssl>=16.1.0

### ISSUE THREAD

**Issue by anthraxx** [eventlet/eventlet#362] opened 2016-12-18 23:30 UTC
Hi, I'm a package maintainer and the tests seem to fail in 0.20:

```
======================================================================
FAIL: test_import_patched_defaults (tests.patcher_test.ImportPatched)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-eventlet/src/eventlet-0.20.0-py2/tests/patcher_test.py", line 104, in test_import_patched_defaults
    assert 'GreenSocket' in lines[1], repr(output)
AssertionError: "base <module 'eventlet.green.socket' from '/build/python-eventlet/src/eventlet-0.20.0-py2/eventlet/green/socket.pyc'> <module 'urllib' from '/usr/lib/python2.7/urllib.pyc'>\nnewmod <module 'base' from '/tmp/tmpbOyIaB_patcher_test/base.py'> <module 'eventlet.green.socket' from '/build/python-eventlet/src/eventlet-0.20.0-py2/eventlet/green/socket.pyc'> <class 'socket._socketobject'>\n"

----------------------------------------------------------------------
Ran 625 tests in 59.175s

```

**Comment by temoto** [comment] 2016-12-19 00:08
Thanks for report. How do you run tests?

**Comment by anthraxx** [comment] 2016-12-19 00:10
```nosetests -sv tests```

**Comment by temoto** [comment] 2016-12-19 00:26
Please, share maximum details, `uname -a`, `python -V`, `pip freeze`. It doesn't fail like that on my machine.

**Comment by anthraxx** [comment] 2016-12-19 00:51
Python version 3 seems to pass fine, its just python2 build that is failing:

System:
``
Linux buildmachine 4.8.12-2-ARCH #1 SMP PREEMPT Fri Dec 2 20:17:06 CET 2016 x86_64 GNU/Linux
```

python:
```
Python 2.7.12
```

Versions:
```
alabaster==0.7.9
appdirs==1.4.0
Babel==2.3.4
cffi==1.9.1
chardet==2.3.0
cryptography==1.7.1
dnspython==1.15.0
docutils==0.13.1
enum34==1.1.6
funcsigs==1.0.2
greenlet==0.4.11
httplib2==0.9.2
idna==2.1
imagesize==0.7.1
ipaddress==1.0.17
Jinja2==2.8
MarkupSafe==0.23
mock==2.0.0
nose==1.3.7
packaging==16.8
pbr==1.10.0
ply==3.9
psycopg2==2.6.2
pyasn1==0.1.9
pycparser==2.17
Pygments==2.1.3
pyOpenSSL==16.2.0
pyparsing==2.1.10
pytz==2016.10
pyzmq==16.0.0
requests==2.12.4
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.1
sphinx-rtd-theme==0.1.9
subprocess32==3.2.7
urllib3==1.19.1
```

**Comment by temoto** [comment] 2016-12-21 15:55
Does it fail when you run `nosetests -sv tests/patcher_test.py` ?

Can you share system image? I've installed latest Arch in Virtualbox, but still cannot reproduce this.

**Comment by anthraxx** [comment] 2016-12-21 16:05
well I'm **really** **really** sry, i translated the nosetests call as i did not expect you to install Arch and we ship   nosetests2 for python2 :stuck_out_tongue: 
so its calling ```nosetests2 -sv tests``` and yes, it also fails for me when doing ```nosetests2 -sv tests/patcher_test.py```

If that does not break, you should not need a system image as we use a deterministic build environment for packaging. If the call above does not already fail, you can simply try by installing ```devtools``` package and use the ```extra-i686-build``` executable in the directory where the ```PKGBUILD``` packaging script is (it will setup a chroot).
the ```PKGBUILD``` file can be obtained from here: https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/python-eventlet

if you want to investigate inside the container, you can use ```sudo arch-nspawn /var/lib/archbuild/extra-i686/YOURUSERNAMEHERE```.

**Comment by temoto** [comment] 2016-12-21 16:14
Are you running pacman installed nose then? Is it all not in virtualenv?

**Comment by anthraxx** [comment] 2016-12-21 16:16
yes, all system packages as eventlet itself is a system package. no virtualenvs involved

**Comment by temoto** [comment] 2016-12-21 22:44
It is triggered by pyopenssl install. What fun.

**Comment by temoto** [comment] 2016-12-22 01:41
Should be fixed in master. Please, try again with latest code.

`pip install https://github.com/eventlet/eventlet/archive/master.zip`

**Comment by anthraxx** [comment] 2016-12-22 23:31
well... progress.... but now i get the following failure :stuck_out_tongue_closed_eyes: 
(yet again only in python2, python3 passes) using latest HEAD: e1bb2fee1db118a617b674821d1f73add9e4f77f

```
======================================================================
FAIL: tests.patcher_test.test_import_patched_defaults
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-eventlet-git/src/python-eventlet-git-py2/tests/patcher_test.py", line 97, in test_import_patched_defaults
    assert output.rstrip() == b'pass', repr(output)
AssertionError: "Fail. Target socket not green: <class 'socket._socketobject'> bases (<type 'object'>,)\n"
```

**Comment by temoto** [comment] 2016-12-23 01:33
This is the same error, just a bit clearer now.
For some reason it wasn't fixed. HEAD PKGBUILD is super useful, thanks.

**Comment by temoto** [comment] 2016-12-23 03:12
Should've say it earlier, but this *could be* a very important error, please don't release 0.20 on Arch before this is fixed.

**Comment by temoto** [comment] 2016-12-29 10:53
*(notebook)*
The issue is caused by freaking import order.

The test in question verifies if `urllib.socket` refers to green module. But mere `import eventlet` to get `import_patched` follows this chain: `eventlet -> .green.base -> OpenSSL -> urllib -> socket`. So `urllib` imports system (not green) `socket` before anything useful happens.

I have a patch that fixes this problem, but it changes `import_patched` semantics quite a lot. Maybe it's a good change though.

New `import_patched()` traces intermediate imports and changes top level imports of patchable modules to green versions. Example:

```
# work.py
import tool
...

# tool.py
import socket  # import_patched now does `tool.socket = eventlet.green.socket`
from socket import getaddrinfo  # this will not be patched

# main.py
import eventlet
eventlet.import_patched('work')
```

**Comment by temoto** [comment] 2016-12-29 23:56
Okay I've finally traced the issue not to Eventlet change but to PyOpenSSL change between 16.0.0 and 16.1.0. Our tox is configured to install pyopenssl 16.0.0 which doesn't trigger this error.

I'll close this issue with little test calmer. The big behavior change can wait little longer.

**Comment by temoto** [comment] 2016-12-30 04:26
Fix is merged to master.

**Comment by temoto** [comment] 2016-12-30 04:27
@anthraxx  Fix is merged to master. Please, try again with latest code.

pip2 install https://github.com/eventlet/eventlet/archive/master.zip

**Comment by anthraxx** [comment] 2016-12-31 19:14
@temoto it seems this particular issue is resolved and all tests seem to pass fine, thanks a lot for your work and creativity to track this down, good job.
Jowever i encountered another python2 issue while running the packaging/install phase on setuptools. Do you want a separated issue for tracking that?

```
byte-compiling /build/python-eventlet-git/pkg/python2-eventlet-git/usr/lib/python2.7/site-packages/eventlet/green/http/client.py to client.pyc
  File "/usr/lib/python2.7/site-packages/eventlet/green/http/client.py", line 195
    _is_legal_header_name = re.compile(rb'[^:\s][^:\r\n]*\Z').match
                                                           ^
SyntaxError: invalid syntax

byte-compiling /build/python-eventlet-git/pkg/python2-eventlet-git/usr/lib/python2.7/site-packages/eventlet/green/http/cookies.py to cookies.pyc
byte-compiling /build/python-eventlet-git/pkg/python2-eventlet-git/usr/lib/python2.7/site-packages/eventlet/green/http/cookiejar.py to cookiejar.pyc
  File "/usr/lib/python2.7/site-packages/eventlet/green/http/cookiejar.py", line 1269
    yield from deepvalues(obj)
             ^
SyntaxError: invalid syntax


```

**Comment by temoto** [comment] 2017-01-01 18:16
Yup. https://github.com/eventlet/eventlet/issues/369

**Closed by temoto** 2017-01-01 18:16 UTC
Labels: enhancement
