### ISSUE TITLE
Pin dnspython<2

### ISSUE THREAD

**Issue by ldruschk** [eventlet/eventlet#629] opened 2020-07-17 17:56 UTC
Starting today with the release of `dnspython==2.0.0`, using pymongo in a flask app running with gunicorn with eventlet workers breaks when using a hostname for the Mongo DB instead of an IP. I have not had time to investigate this issue in-depth, but pinning `dnspython<2` works as expected. I will see if I can add some more info later.

cc @trolldemorted @mauricesvp @mmunier (for updates in this issue)

**Comment by ldruschk** [comment] 2020-07-17 17:57
For some more details, running the same app with default gunicorn workers also works as expected and using pymongo directly works as well, only when running gunicorn with eventlet workers the issue begins appearing

**Comment by Trolldemorted** [comment] 2020-07-17 18:07
It would also be great if you'd not use `>=`, we just lost several hours finding out why our code stopped working :|

**Comment by eacmen** [comment] 2020-07-17 21:51
related to #619. Pinning dnspython for now would be the prudent move.

**Comment by ldruschk** [comment] 2020-07-17 21:58
Ah indeed, I must have overlooked that because I didn't go that far back in issues since I assumed that the issue was quite new

**Comment by elunty** [comment] 2020-07-17 22:04
Same here Trolldemorted. But also i should have done a pip freeze compare of my environments earlier to see what was up. Oh well..

**Comment by ralonsoh** [comment] 2020-07-20 17:34
3029618 is not correct (missing return). 
46fc185 is supposed to work with dnspython <2.0.0 and 2.0.0

**Comment by firaskafri** [comment] 2020-07-21 19:17
Almost got to production!

**Comment by eacmen** [comment] 2020-07-21 19:21
I don't understand why eventlet devs wouldn't merge #630 until this issue is resolved. Any container builds that occur while this issue is open will almost certainly result in a broken container.

**Comment by nolash** [comment] 2020-07-23 06:05
This took many hours off us aswell. _Please_ specify deps within major number versions.

**Comment by iROCKBUNNY** [comment] 2020-07-24 10:27
Any progress on this? This took me many hours, too. Now I am just using dnspython==1.16.0 for a temporary workaround.

**Comment by greatvovan** [comment] 2020-07-24 17:56
One more developer is here, who spent few hours investigating DNS timeout issue after a Docker image rebuild. The most recent version is basically broken now.

**Comment by temoto** [comment] 2020-07-30 17:11
Everybody affected by this problem with a free minute is warmly invited to test Rodolfo solution.

(this is his commit rebased on master 0.26)
`pip install https://github.com/eventlet/eventlet/archive/adb2eebc14cbdd00f572a8f36b5e9cb6994b6d42.zip`

**Comment by jamesbraza** [comment] 2020-07-30 17:28
I just tested, and it seems to be working!  Coming from here: https://github.com/rthalley/dnspython/issues/557 --> https://github.com/rthalley/dnspython/issues/559

**Comment by rthalley** [comment] 2020-07-30 17:33
Fails for me still with the situation the original poster reported, namely calling the resolver:

```
import eventlet.support.greendns as gd
p = gd.ResolverProxy()
try:
    a = p.query('www.dnspython.org')
    print(a.rrset)
except Exception as e:
    print('bad', e)
```

This will result in `dns.exception.Timeout: The DNS operation timed out after 5.121809005737305 seconds`

for the AttributeError reasons I described in #619

**Comment by temoto** [comment] 2020-07-30 21:58
Thanks for testing. v0.26.1 just uploaded to PyPI with temporary workaround by @eacmen pin `dnspython<2`

I'm closing this issue because it particularly targets pin workaround.
The root cause of insufficient patching is still there. Please subscribe #619

**Closed by temoto** 2020-07-30 21:58 UTC
