### ISSUE TITLE
eventlet 0.18.2 broken an unit test of OpenStack Keystone

### ISSUE THREAD

**Issue by haypo** [eventlet/eventlet#296] opened 2016-02-10 13:03 UTC
Discussion on the commit: https://github.com/eventlet/eventlet/commit/5bf0a6f32b3e4459b38ad1895c9eb4b0b483dae1#commitcomment-16002966

Traceback:

```
Traceback (most recent call last):
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 850, in server
    serv.pid, socket_repr(sock)))
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 254, in info
    self.write(msg, *args)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 264, in write
    writeall(self.log, msg)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/support/__init__.py", line 72, in writeall
    written += fd.write(buf[written:])
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".tox/py34/lib/python3.4/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
    timer()
  File ".tox/py34/lib/python3.4/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "keystone/common/environment/eventlet_server.py", line 206, in _run
    socket_timeout=socket_timeout)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 874, in server
    serv.pid, is_accepting))
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 254, in info
    self.write(msg, *args)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/wsgi.py", line 264, in write
    writeall(self.log, msg)
  File ".tox/py34/lib/python3.4/site-packages/eventlet/support/__init__.py", line 72, in writeall
    written += fd.write(buf[written:])
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

Workaround: skip the test in Keystone, https://review.openstack.org/#/c/278147/

**Comment by haypo** [comment] 2016-02-10 13:05
This bug is related the issue #295.

**Comment by temoto** [comment] 2016-02-10 13:15
Thanks, fix is coming soon.

**Comment by haypo** [comment] 2016-02-10 13:16
Sorry, I lost track of the discussion, but IMHO the safer option is to restore "sendall" behaviour for eventlet socket send(). It would avoid the need of custom writelines() only used in wsgi.

**Comment by temoto** [comment] 2016-02-10 13:33
I'm not saying `safe_writelines` must be fixed or there is need in it.

**Comment by haypo** [comment] 2016-02-10 14:40
The write() method returning None comes from keystone.common.environment.eventlet_server.EventletFilteringLogger(). It doesn't use any socket:

https://github.com/openstack/keystone/blob/7a0874f6f69852584061fa384f75dfb0d5f1c229/keystone/common/environment/eventlet_server.py#L61

**Comment by haypo** [comment] 2016-02-10 16:20
A trivial fix for eventlet is to stop the writeall() loop if write() returns None.

**Comment by jstasiak** [comment] 2016-02-10 23:42
@haypo ``send()`` behaving like ``sendall()`` is a source of very subtle issues when sockets with timeout are used so I don't think we should be restoring that behaviour.

Regarding handling ``None`` in ``writeall()`` - it's not that trivial, ``RawIOBase.write()`` can return None when "the raw stream is set not to block and no single byte could be readily written to it"[1] so just breaking out of the loop could hide an issue if ``writeall()`` ever was passed such stream (not particularly probable case but that makes it even subtler if it happens).

As far as the issue reported is concerned - ``eventlet.wsgi.server`` documentation is quite clear in this regard - the ``log`` object passed to it has to be a "File-like object"[2] and on Python 3 all builtin file-like objects I could find except for ``mmap.mmap`` have ``write()`` methods that return the number of elements written[3]. Considering this may I suggest a change in``EventletFilteringLogger.write()`` to satisfy this requirement and return the number of bytes "written"?

[1] https://docs.python.org/3/library/io.html#io.RawIOBase.write
[2] http://eventlet.net/doc/modules/wsgi.html#eventlet.wsgi.server
[3] https://docs.python.org/3/library/io.html

**Comment by temoto** [comment] 2016-02-11 15:14
Yup, file object returning None means `writeall` must go into infinite retry loop.

`eventlet.wsgi` is still going to loose custom write function, so symptoms of this issue will be fixed, but it's not a bug.

**Comment by temoto** [comment] 2016-02-12 17:29
Fixed in master.

**Closed by temoto** 2016-02-12 17:29 UTC
Labels: invalid
