### ISSUE TITLE
Eventlet and multiprocessing

### ISSUE THREAD

**Issue by mdomans** [eventlet/eventlet#425] opened 2017-07-13 04:54 UTC
Hi, this is a pretty interesting one for me - if I enable Eventlet patching of django via `eventlet.monkey_patch()` in **manage.py** the processes(prefork) pool doesn't work.

Patching with `eventlet.monkey_patch(thread=False)` makes both Eventlet based and processes based pools work for the same code base, but raises some pretty bad DB issues and eventlet worker can only be stopped via SIGKILL

Is this something obvious I'm not understanding or is this error caused by how internally process based pool works?

Concurrency docs for Celery are pretty poor so if someone has a hint where to search, I welcome any help

libs:
Django 1.11.2
Celery 3.1.25
MySQL-python 1.2.5
pylibmc 1.5.0

**Comment by mdomans** [comment] 2017-07-13 05:13
Found this in gevent code, seems to be related:

>  Description of the hang:
 > There is an incompatibility with patching 'thread' and the 'multiprocessing' module:
 >  The problem is that multiprocessing.queues.Queue uses a half-duplex multiprocessing.Pipe,
 >  which is implemented with os.pipe() and _multiprocessing.Connection. os.pipe isn't patched
    by gevent, as it returns just a fileno. _multiprocessing.Connection is an internal implementation
    class implemented in C, which exposes a 'poll(timeout)' method; under the covers, this issues a
    (blocking) select() call: hence the need for a real thread. Except for that method, we could
    almost replace Connection with gevent.fileobject.SocketAdapter, plus a trivial
    patch to os.pipe (below). Sigh, so close. (With a little work, we could replicate that method)

Am I on the right track?

**Comment by temoto** [comment] 2017-07-13 06:38
Yes, Eventlet monkey patching is also not fully compatible with multiprocessing.
Duplicate of #210 

If you need multiprocessing more, I can only suggest drop `monkey_patch()` and use green modules directly or `import_patched` modules that contain blocking code.

If you need concurrency more, drop multiprocessing in favor of process pool specialised for your task.

**Closed by temoto** 2017-07-13 06:38 UTC
