### ISSUE TITLE
TypeError: wrap_socket() argument 1 must be _socket.socket, not GreenSocket

### ISSUE THREAD

**Issue by andresm66** [eventlet/eventlet#201] opened 2015-02-16 10:26 UTC
Hi so Im having this issue whenever i try to open an https url, im not sure if im doing something wrong but i even get this with just the example on ssl usage from the website 

```
from eventlet.green import urllib2
from eventlet import spawn
bodies = [spawn(urllib2.urlopen, url)
     for url in ("https://secondlife.com","https://google.com")]
for b in bodies:
    print(b.wait().read())
```

**Comment by jstasiak** [comment] 2015-02-16 18:01
Hi, can you provide the following please? It should make understanding the issue easier.

* Python version
* Eventlet version
* full stack trace

**Comment by andresm66** [comment] 2015-02-16 18:15
yeah sorry here it is

python version 2.7.9
Eventlet 0.16.1

Traceback (most recent call last): File "", line 2, in File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/eventlet/greenthread.py", line 175, in wait return self._exit_event.wait() File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/eventlet/event.py", line 121, in wait return hubs.get_hub().switch() File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 294, in switch return self.greenlet.switch() File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/eventlet/greenthread.py", line 214, in main result = function(*args, **kwargs) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open response = self._open(req, data) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open '_open', req) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain result = func(*args) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open context=self._context) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1194, in do_open h.request(req.get_method(), req.get_selector(), req.data, headers) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request self._send_request(method, url, body, headers) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request self.endheaders(body) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders self._send_output(message_body) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output self.send(msg) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send self.connect() File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1212, in connect server_hostname=server_hostname) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket _context=self) File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 560, in init server_hostname, ssl_sock=self) TypeError: _wrap_socket() argument 1 must be _socket.socket, not GreenSocket

**Comment by temoto** [comment] 2015-02-16 20:05
Formatted. Surround with triple backquote (```) to paste code in Github.

**Comment by shakeelmohamed** [comment] 2015-02-27 02:47
+1

**Comment by benmao** [comment] 2015-03-29 01:25
+1

**Comment by temoto** [comment] 2015-03-29 09:01
Update: it only breaks in CPython 2.7.9. Versions 2.7.6 and 2.7.8 work.

**Comment by temoto** [comment] 2015-03-29 11:54
Nailed the root cause: Eventlet doesn't patch `ssl.SSLContext.wrap_context`. So far httplib doesn't recognize my patched SSLContext. To be continued.

**Comment by temoto** [comment] 2015-03-29 12:36
@andresm66 @shakeelmohamed @benmao please test https://github.com/eventlet/eventlet/commit/b2e5146dec8f6fe075884dcf788f64a16bc3fec3
What we are looking for is urllib2.urlopen works with HTTPS, but everything else also works as before.
Additional gratitude for testing it with any other Python versions.

You can install this particular version with `pip install https://github.com/eventlet/eventlet/archive/b2e5146dec8f6fe075884dcf788f64a16bc3fec3.zip`
If unsure, I recommend doing this in virtualenv.

**Comment by shakeelmohamed** [comment] 2015-03-29 22:51
@temoto Yep that worked!

I added @andresm66's script to `test.py` then ran the following (which got the expected error):
```shell
pyenv local 2.7.9
pip install eventlet
python test.py
```

Then installed the updated eventlet, and it worked:

```shell
pip uninstall eventlet
pip install https://github.com/eventlet/eventlet/archive/b2e5146dec8f6fe075884dcf788f64a16bc3fec3.zip
python test.py
```

**Comment by benmao** [comment] 2015-03-30 00:07
@temoto You did a good job.

**Comment by temoto** [comment] 2015-03-30 08:28
Thanks for testing, the fix is merged into master and will land in upcoming bug fix release.

**Closed by temoto** 2015-03-30 08:28 UTC
Labels: bug, need-test

**Comment by andresm66** [comment] 2015-03-30 17:13
sorry i couldn't test it earlier i was kinda busy with the work, either way i have installed the version and it works now, thanks for the fix, and I'm looking forward to see the next update

**Comment by temoto** [comment] 2015-04-03 02:56
FYI: fix is included in v0.17.2 release, available on PyPi.

**Comment by motoom** [comment] 2020-10-29 11:19
I'm experiencing this error too, on Python 3.8.5, on OSX.

Code to reproduce:

```
#!/usr/bin/env python3

import gevent.monkey
gevent.monkey.patch_socket()

import gevent
from urllib.request import urlopen

resp = urlopen('https://my-json-server.typicode.com/typicode/demo/comments')
```

Stack trace:

```
Traceback (most recent call last):
  File "/Users/user/Prj/python/gevent-tutorial/sockerror.py", line 9, in 
    resp = urlopen('https://my-json-server.typicode.com/typicode/demo/comments')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1031, in _create
    self._sslobj = self._context._wrap_socket(
TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket
```

**Comment by temoto** [comment] 2020-10-29 12:25
@motoom it seems similar but gevent is another library, you may ask there https://github.com/gevent/gevent

**Comment by artemchege** [comment] 2022-07-08 16:02
> I'm experiencing this error too, on Python 3.8.5, on OSX.
> 
> Code to reproduce:
> 
> ```
> #!/usr/bin/env python3
> 
> import gevent.monkey
> gevent.monkey.patch_socket()
> 
> import gevent
> from urllib.request import urlopen
> 
> resp = urlopen('https://my-json-server.typicode.com/typicode/demo/comments')
> ```
> 
> Stack trace:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/user/Prj/python/gevent-tutorial/sockerror.py", line 9, in 
>     resp = urlopen('https://my-json-server.typicode.com/typicode/demo/comments')
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
>     self.connect()
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1031, in _create
>     self._sslobj = self._context._wrap_socket(
> TypeError: _wrap_socket() argument 'sock' must be _socket.socket, not SSLSocket
> ```

Had the same issue. 
Just: 

  import gevent.monkey
  gevent.monkey.patch_all(ssl=True)
  import requests

make thid patch before importing requests
