### ISSUE TITLE
eventlet 0.18.0 breaks Nova, KeyStone and other OpenStack jobs

### ISSUE THREAD

**Issue by dims** [eventlet/eventlet#290] opened 2016-01-24 03:32 UTC
Examples of failures:
https://bugs.launchpad.net/keystone/+bug/1537401
https://bugs.launchpad.net/nova/+bug/1537402

Typical traceback:
2016-01-23 22:27:15.045 7298 ERROR nova   File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
2016-01-23 22:27:15.045 7298 ERROR nova     return self._communicate(input)
2016-01-23 22:27:15.045 7298 ERROR nova   File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate
2016-01-23 22:27:15.045 7298 ERROR nova     stdout, stderr = self._communicate_with_poll(input)
2016-01-23 22:27:15.045 7298 ERROR nova   File "/usr/lib/python2.7/subprocess.py", line 1439, in _communicate_with_poll
2016-01-23 22:27:15.045 7298 ERROR nova     poller = select.poll()
2016-01-23 22:27:15.045 7298 ERROR nova AttributeError: 'module' object has no attribute 'poll'

**Comment by dims** [comment] 2016-01-24 03:32
logstash query (for OpenStack logstash instance http://logstash.openstack.org/):
message:"AttributeError: 'module' object has no attribute 'poll'"

**Comment by dims** [comment] 2016-01-24 03:37
Guess this was done by design:
https://github.com/eventlet/eventlet/blob/2865c23837980c987e79562d15633ef4a032b8c6/NEWS#L38

**Comment by dianaclarke** [comment] 2016-01-24 07:26
There is also this (different) OpenStack bug with eventlet 0.18.0:

    TypeError: an integer is required
    https://bugs.launchpad.net/nova/+bug/1537450

Which is related to the "Handle blocking I/O errors in GreenSocket" changes:

    https://github.com/eventlet/eventlet/issues/274
    https://github.com/eventlet/eventlet/commit/bc4d1b5d362e5baaeded35b1e339b9db08172dd2

If I rollback those changes in eventlet/greenio/base.py, the error goes away.

I don't currently have a standalone script to reproduce this error (sorry!), but @haypo will know how to reproduce it by running the nova functional tests. In particular:

tox -e functional nova.tests.functional.api_sample_tests.test_cloudpipe.CloudPipeSampleTest

**Comment by jstasiak** [comment] 2016-01-24 09:05
Hi, thanks for the report. It's been done by design but it's not meant to break subprocess. The only way I see the patch breaking subprocess module right now is when monkey patching is done and it happens after subprocess is already imported - can you confirm whether that is or isn't the case?

**Comment by temoto** [comment] 2016-01-24 14:58
Any order of import should not break subprocess.

**Comment by dims** [comment] 2016-01-24 17:03
@temoto, here's a simple recreate

dims@ubuntu-vm:~$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02)
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> print eventlet.__version__
0.18.0
>>> import subprocess
>>> import eventlet
>>> eventlet.monkey_patch(all=True)
>>> p = subprocess.Popen(['ls'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>>> print p.communicate()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1440, in _communicate_with_poll
    poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'
>>>

**Comment by dims** [comment] 2016-01-24 17:05
@jstasiak yes, please see previous comment

**Comment by temoto** [comment] 2016-01-24 17:25
Thanks for reproduction code. It also fails on Python 3.4, but it requires Linux, on Mac OSX there's no error.

**Comment by temoto** [comment] 2016-01-24 19:39
Revert-like bugfix was released in v0.18.1
`subprocess .communicate()` is fixed.
Proper fix is to have green version of `select.poll()`.

**Closed by temoto** 2016-01-24 19:39 UTC

**Comment by dims** [comment] 2016-01-24 20:01
@temoto thanks a ton!
