### ISSUE TITLE
RuntimeError('no suitable implementation for this system')

### ISSUE THREAD

**Issue by JacoFourie** [eventlet/eventlet#419] opened 2017-06-13 07:14 UTC
Hi.

I get RuntimeError('no suitable implementation for this system') when I use Eventlet on Ubuntu Desktop 17.04
/usr/local/lib/python2.7/dist-packages/eventlet/support/monotonic.py

All is working on Rasbian or a Raspberry Pi. I moved the code to a Ubuntu desktop and now I get this error.

I did install the latest Eventlet fom the Master.zip file

**Comment by temoto** [comment] 2017-06-13 07:31
Duplicate of #401

**Closed by temoto** 2017-06-13 07:31 UTC
Labels: resolution-duplicate
