### ISSUE TITLE
Removal of select.poll() causing failures in subprocess code

### ISSUE THREAD

**Issue by stmcginnis** [eventlet/eventlet#398] opened 2017-03-21 17:08 UTC
The _communicate_with_poll call in subprocess.py [0] calls select.poll(). After eventlet monkey patches this module and removes that call, consuming code fails with "AttributeError: 'module' object has no attribute 'poll'"

[0] https://svn.python.org/projects/python/trunk/Lib/subprocess.py

**Comment by stmcginnis** [comment] 2017-03-21 17:09
Instance of failure: http://logs.openstack.org/70/446370/4/check/gate-manila-docs-ubuntu-xenial/e8abd62/console.html#_2017-03-21_12_21_49_449167

**Comment by dims** [comment] 2017-03-21 17:13
Looking at where things changed:
https://github.com/eventlet/eventlet/commit/614a20462aebfe85a54ce35a7daaf1a7dbde44a7#diff-a51187cea073d644e058c9e92c7a2ef9

previous issue:
https://github.com/eventlet/eventlet/issues/290

**Comment by temoto** [comment] 2017-03-21 18:42
Trace originates in `setup.py`, let me guess there was no `eventlet.monkey_patch()` call there, but `eventlet` module was imported?

**Comment by stmcginnis** [comment] 2017-03-21 18:44
Correct. Currently worked around by doing that, but I'm really opposed to making that workaround everywhere this pops up.

**Comment by temoto** [comment] 2017-03-21 18:54
Duplicate of #240 you may wish to subscribe for notifications on that issue.

Thanks for reminder, I'll try to make it sooner.

**Closed by temoto** 2017-03-21 18:54 UTC
Labels: importance-bug, resolution-duplicate
