### ISSUE TITLE
0.31.0: pytest based test suite is failing

### ISSUE THREAD

**Issue by kloczek** [eventlet/eventlet#704] opened 2021-05-08 07:28 UTC
Looks like eventlet uses `test` and `urllib2` modules. I cannot find both.
May I ask for advice?
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-eventlet-0.31.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-eventlet-0.31.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, flaky-3.7.0, mock-3.6.0, hypothesis-6.12.0, asyncio-0.15.1
collected 696 items / 22 errors / 674 selected

================================================================================== ERRORS ==================================================================================
__________________________________________________________ ERROR collecting tests/stdlib/test_SimpleHTTPServer.py __________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_SimpleHTTPServer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_SimpleHTTPServer.py:2: in <module>
    from eventlet.green import SimpleHTTPServer
eventlet/green/SimpleHTTPServer.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'SimpleHTTPServer'
______________________________________________________________ ERROR collecting tests/stdlib/test_asynchat.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_asynchat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_asynchat.py:9: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
______________________________________________________________ ERROR collecting tests/stdlib/test_asyncore.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_asyncore.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_asyncore.py:8: in <module>
    patcher.inject("test.test_asyncore", globals())
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_ftplib.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_ftplib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_ftplib.py:7: in <module>
    patcher.inject('test.test_ftplib', globals())
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
______________________________________________________________ ERROR collecting tests/stdlib/test_httplib.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_httplib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_httplib.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
____________________________________________________________ ERROR collecting tests/stdlib/test_httpservers.py _____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_httpservers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_httpservers.py:4: in <module>
    from eventlet.green import SimpleHTTPServer
eventlet/green/SimpleHTTPServer.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'SimpleHTTPServer'
_________________________________________________________________ ERROR collecting tests/stdlib/test_os.py _________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_os.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_os.py:4: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_queue.py ________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_queue.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_queue.py:6: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_select.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_select.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_select.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_socket.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_socket.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_socket.py:10: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_____________________________________________________________ ERROR collecting tests/stdlib/test_socket_ssl.py _____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_socket_ssl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_socket_ssl.py:7: in <module>
    import test.test_support
E   ModuleNotFoundError: No module named 'test'
____________________________________________________________ ERROR collecting tests/stdlib/test_socketserver.py ____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_socketserver.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_socketserver.py:11: in <module>
    from test import test_support
E   ModuleNotFoundError: No module named 'test'
________________________________________________________________ ERROR collecting tests/stdlib/test_ssl.py _________________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_ssl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_ssl.py:7: in <module>
    from eventlet.green import SimpleHTTPServer
eventlet/green/SimpleHTTPServer.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'SimpleHTTPServer'
_____________________________________________________________ ERROR collecting tests/stdlib/test_subprocess.py _____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_subprocess.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_subprocess.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_thread.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_thread.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_thread.py:6: in <module>
    patcher.inject('test.test_thread', globals())
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_________________________________________________________ ERROR collecting tests/stdlib/test_thread__boundedsem.py _________________________________________________________
tests/stdlib/test_thread__boundedsem.py:16: in <module>
    execfile(os.path.join(os.path.dirname(__file__), 'test_thread.py'))
E   NameError: name 'execfile' is not defined
_____________________________________________________________ ERROR collecting tests/stdlib/test_threading.py ______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_threading.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_threading.py:9: in <module>
    patcher.inject('test.test_threading',
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
__________________________________________________________ ERROR collecting tests/stdlib/test_threading_local.py ___________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_threading_local.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_threading_local.py:10: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
______________________________________________________________ ERROR collecting tests/stdlib/test_timeout.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_timeout.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_timeout.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
_______________________________________________________________ ERROR collecting tests/stdlib/test_urllib.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_urllib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_urllib.py:5: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'test'
______________________________________________________________ ERROR collecting tests/stdlib/test_urllib2.py _______________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_urllib2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_urllib2.py:3: in <module>
    from eventlet.green import urllib2
eventlet/green/urllib2.py:9: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'urllib2'
__________________________________________________________ ERROR collecting tests/stdlib/test_urllib2_localnet.py __________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/stdlib/test_urllib2_localnet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/stdlib/test_urllib2_localnet.py:6: in <module>
    from eventlet.green import urllib2
eventlet/green/urllib2.py:9: in <module>
    patcher.inject(
eventlet/patcher.py:109: in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
E   ModuleNotFoundError: No module named 'urllib2'
============================================================================= warnings summary =============================================================================
eventlet/debug.py:16
  /home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/eventlet/debug.py:16: DeprecationWarning: invalid escape sequence \W
    _token_splitter = re.compile('\W+')

tests/pools_test.py:248
  /home/tkloczko/rpmbuild/BUILD/eventlet-0.31.0/tests/pools_test.py:248: PytestCollectionWarning: cannot collect test class 'TestTookTooLong' because it has a __init__ constructor (from: tests/pools_test.py)
    class TestTookTooLong(Exception):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR tests/stdlib/test_SimpleHTTPServer.py
ERROR tests/stdlib/test_asynchat.py
ERROR tests/stdlib/test_asyncore.py
ERROR tests/stdlib/test_ftplib.py
ERROR tests/stdlib/test_httplib.py
ERROR tests/stdlib/test_httpservers.py
ERROR tests/stdlib/test_os.py
ERROR tests/stdlib/test_queue.py
ERROR tests/stdlib/test_select.py
ERROR tests/stdlib/test_socket.py
ERROR tests/stdlib/test_socket_ssl.py
ERROR tests/stdlib/test_socketserver.py
ERROR tests/stdlib/test_ssl.py
ERROR tests/stdlib/test_subprocess.py
ERROR tests/stdlib/test_thread.py
ERROR tests/stdlib/test_thread__boundedsem.py - NameError: name 'execfile' is not defined
ERROR tests/stdlib/test_threading.py
ERROR tests/stdlib/test_threading_local.py
ERROR tests/stdlib/test_timeout.py
ERROR tests/stdlib/test_urllib.py
ERROR tests/stdlib/test_urllib2.py
ERROR tests/stdlib/test_urllib2_localnet.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 22 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================================== 2 warnings, 22 errors in 1.95s ======================================================================
```

**Comment by jstasiak** [comment] 2021-05-08 07:33
Hey, running the test suite using pytest is not supported until the project switches from nose to pytest.

**Comment by temoto** [comment] 2021-05-08 07:36
Duplicate of https://github.com/eventlet/eventlet/issues/638

**Closed by temoto** 2021-05-08 07:36 UTC
Labels: resolution-duplicate

**Comment by kloczek** [comment] 2023-01-20 05:43
> Hey, running the test suite using pytest is not supported until the project switches from nose to pytest.

On migration to pytest usefull could be https://github.com/schollii/nose2pytest/
