### ISSUE TITLE
processes are consuming more than 90% of CPU when calling send method in eventlet/greenio.py

### ISSUE THREAD

**Issue by XuhuiMiao** [eventlet/eventlet#192] opened 2015-01-21 05:49 UTC
[Scenario]
1. Start rsyslog server.
2. Run our application.
3. Stop rsyslog server
4. Trigger a syslog in our application.
5. The thread of logging consumes 90+% of cpu.

[Description]
According to debug result, we found an endless loop found in send method, the send method would be blocked when no data was sent as description in the document(greenio.py), but unfortunately the send method returned immediately, and the return value was 107( "'Transport endpoint is not connected'"). The return value will raise an exception in Windows System but not in Linux System. I think It is lack of consideration for all cases of the return value in Linux System. 
```
/usr/lib/python2.6/site-packages/eventlet/greenio.py
if sys.platform[:3] == "win":
    # winsock sometimes throws ENOTCONN
    SOCKET_BLOCKING = set((errno.EAGAIN, errno.EWOULDBLOCK,))
    SOCKET_CLOSED = set((errno.ECONNRESET, errno.ENOTCONN, errno.ESHUTDOWN))
else:
    # oddly, on linux/darwin, an unconnected socket is expected to block,
    # so we treat ENOTCONN the same as EWOULDBLOCK
    SOCKET_BLOCKING = set((errno.EAGAIN, errno.EWOULDBLOCK, errno.ENOTCONN))
    SOCKET_CLOSED = set((errno.ECONNRESET, errno.ESHUTDOWN, errno.EPIPE))

/usr/lib/python2.6/site-packages/eventlet/greenio.py
    def send(self, data, flags=0):
        fd = self.fd
        if self.act_non_blocking:
            return fd.send(data, flags)

        # blocking socket behavior - sends all, blocks if the buffer is full
        total_sent = 0
        len_data = len(data)
        while 1:
            try:
                total_sent += fd.send(data[total_sent:], flags)
            except socket.error as e:
                if get_errno(e) not in SOCKET_BLOCKING:
                    raise

            if total_sent == len_data:
                break

            try:
                self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
                           timeout_exc=socket.timeout("timed out"))
            except IOClosed:
                raise socket.error(errno.ECONNRESET, 'Connection closed by another thread')

        return total_sent

[Debug]
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(346)send()
-> try:
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(347)send()
-> total_sent += fd.send(data[total_sent:], flags)
(Pdb) n
error: (107, 'Transport endpoint is not connected')
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(347)send()
-> total_sent += fd.send(data[total_sent:], flags)
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(348)send()
-> except socket.error as e:
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(349)send()
-> if get_errno(e) not in SOCKET_BLOCKING:
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(352)send()
-> if total_sent == len_data:
(Pdb) p total_sent,len_data
(0, 121)
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(355)send()
-> try:
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(356)send()
-> self._trampoline(self.fd, write=True, timeout=self.gettimeout(),
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(357)send()
-> timeout_exc=socket.timeout("timed out"))
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(346)send()
-> try:
(Pdb) n
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(347)send()
-> total_sent += fd.send(data[total_sent:], flags)
(Pdb)



(Pdb) bt
  /usr/lib/python2.6/site-packages/eventlet/greenpool.py(82)_spawn_n_impl()
-> func(*args, **kwargs)
  /usr/lib/python2.6/site-packages/eventlet/wsgi.py(661)process_request()
-> proto.__init__(sock, address, self)
  /usr/lib64/python2.6/SocketServer.py(627)__init__()
-> self.handle()
  /usr/lib64/python2.6/BaseHTTPServer.py(329)handle()
-> self.handle_one_request()
  /usr/lib/python2.6/site-packages/eventlet/wsgi.py(321)handle_one_request()
-> self.handle_one_response()
  /usr/lib/python2.6/site-packages/eventlet/wsgi.py(433)handle_one_response()
-> result = self.application(self.environ, start_response)
  /usr/lib/python2.6/site-packages/webob/dec.py(130)__call__()
-> resp = self.call_func(req, *args, **self.kwargs)
  /usr/lib/python2.6/site-packages/webob/dec.py(195)call_func()
-> return self.func(req, *args, **kwargs)
  /usr/lib/python2.6/site-packages/glance/common/wsgi.py(394)__call__()
-> response = req.get_response(self.application)
  /usr/lib/python2.6/site-packages/webob/request.py(1296)send()
-> application, catch_exc_info=False)
  /usr/lib/python2.6/site-packages/webob/request.py(1260)call_application()
-> app_iter = application(self.environ, start_response)
  /usr/lib/python2.6/site-packages/keystonemiddleware/auth_token.py(720)__call__()
-> 'Invalid user token - deferring reject downstream')
  /usr/lib64/python2.6/logging/__init__.py(1056)info()
-> self._log(INFO, msg, args, **kwargs)
  /usr/lib64/python2.6/logging/__init__.py(1173)_log()
-> self.handle(record)
  /usr/lib64/python2.6/logging/__init__.py(1183)handle()
-> self.callHandlers(record)
  /usr/lib64/python2.6/logging/__init__.py(1220)callHandlers()
-> hdlr.handle(record)
  /usr/lib64/python2.6/logging/__init__.py(679)handle()
-> self.emit(record)
  /usr/lib64/python2.6/logging/handlers.py(801)emit()
-> self.socket.send(msg)
> /usr/lib/python2.6/site-packages/eventlet/greenio.py(357)send()
-> timeout_exc=socket.timeout("timed out"))
```

**Comment by temoto** [comment] 2015-03-28 19:37
Thanks for bug report, and sorry for late reply. CPU burning issues generally have priority, but we have already fixed quite a few of them, so it may be a rare case, so a little more information would help.

* What eventlet version do you use? `python -c 'import eventlet; print(eventlet.__version__)'`
* What Linux distribution is it?
* `uname -a`
* Can you try the same scenario with Python2.7?

**Comment by javacruft** [comment] 2015-05-06 15:31
I think we're seeing this issue with some parts of OpenStack - specifically I can reproduce this problem at will on Ubuntu 14.04 with OpenStack Icehouse Glance - see https://bugs.launchpad.net/ubuntu/+source/python-eventlet/+bug/1452312.

Eventlet in 14.04 is at 0.13.0.

**Comment by temoto** [comment] 2015-05-06 15:59
We've had multiple CPU burning fixes since 0.13, so trying with a more recent version of eventlet is one way to move towards solution.

But there's launchpad comment:
> Also confirmed with kilo - using eventlet 0.16.0

And that's a whole different story, because 0.16 should be CPU usage stable, so this might be a real bug still happening. I will look into this shortly after May 11. Reminders are warmly welcome.

**Comment by javacruft** [comment] 2015-05-06 16:01
To confirm - I see this same issue on 0.16.1 (which is what we released with OpenStack Kilo in Ubuntu).

I can only reproduce this with glance so-far.

**Comment by xtrusia** [comment] 2015-05-14 06:55
I'm not the expert of this. but i had some tries on this code.

when "Transport endpoint is not connected" error occures on send function

it can be catched by except statement but skipped by if statement (SOCKET_BLOCKING has ENOTCONN)

so comes unlimited loop, then hang.

so i put like below on my env

line 349 in send function
####################################################
            except socket.error as e:
                if get_errno(e) not in SOCKET_BLOCKING:
                    raise
                elif get_errno(e) is errno.ENOTCONN:
                    raise
####################################################

I worried about regression when i remove errno.ENOTCONN on SOCKET_BLOCKING, so i just added that lines..

in my env, it works. but I'm not sure this is ok or not..

**Comment by temoto** [comment] 2015-05-15 01:16
@xtrusia thank you very much, I've pushed a commit with your idea but one `get_errno` call and `==` instead of `is` comparison, all credit is still yours of course.
@XuhuiMiao @javacruft please test https://github.com/eventlet/eventlet/commit/ed0655333007fe97624b745e92deb407d192022c

**Comment by temoto** [comment] 2015-05-21 22:28
ping

**Comment by temoto** [comment] 2015-06-13 07:02
Fix is merged in master.

**Closed by temoto** 2015-06-13 07:02 UTC
Labels: bug, need-test
