### ISSUE TITLE
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:2639)

### ISSUE THREAD

**Issue by jxfruit** [eventlet/eventlet#962] opened 2024-05-30 12:36 UTC
python:3.8
evenlet: the latest
flask-socketio:5.3.4
I used the self-signed certification, but it is useless. And got the error: 
Traceback (most recent call last):
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 869, in process_request
    proto.__init__(conn_state, self)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 359, in __init__
    self.handle()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 392, in handle
    self.handle_one_request()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 428, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 409, in _read_request_line
    line = self.rfile.readline(self.server.url_length_limit)
  File "/data/app/miniconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 265, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 280, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 196, in read
    return self._call_trampolining(
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 166, in _call_trampolining
    return func(*a, **kw)
  File "/data/app/miniconda3/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:2639)
Removing descriptor: 88

**Comment by 4383** [comment] 2024-06-03 06:56
Hello,

Which version of Eventlet are you using?

**Comment by jxfruit** [comment] 2024-06-03 07:21
> Hello,
> 
> Which version of Eventlet are you using?

@4383 Eventlet 0.36.1，I tried a few versions, all of them useless.
May I ask for a way of avoiding ssl verification, any parameters passed?

**Comment by 4383** [comment] 2024-06-03 07:49
Well, I'm not sure what happens in your env, can you try to install `pip-system-certs` in version 4.0
https://pypi.org/project/pip-system-certs/

Concerning the ssl verification disabling, I think it is more a on the flask side that you may want to disable this thing... Eventlet do "nothing" it just monkey patch your env. Socket usages are made at another level, like flask, or your own code, I think that that's at this level that you need to disable ssl.

**Comment by 4383** [comment] 2024-06-03 07:53
An example of ssl enabling copied from https://stackoverflow.com/questions/29458548/can-you-add-https-functionality-to-a-python-flask-web-server#42906465

```
from flask import Flask, jsonify


from OpenSSL import SSL
context = SSL.Context(SSL.PROTOCOL_TLSv1_2)
context.use_privatekey_file('server.key')
context.use_certificate_file('server.crt')   


app = Flask(__name__)


@app.route('/')
def index():
    return 'Flask is running!'


@app.route('/data')
def names():
    data = {"names": ["John", "Jacob", "Julie", "Jennifer"]}
    return jsonify(data)


#if __name__ == '__main__':
#    app.run()
if __name__ == '__main__':  
     app.run(host='127.0.0.1', debug=True, ssl_context=context)
```

**Comment by 4383** [comment] 2024-06-03 07:55
So if you don't want ssl, then, I'd suggest you to remove the `ssl_context`.
I think you have more or less the same config on your side.

However, I won't encourage you to disable ssl...
I'd rather encourage your to see if `pip-systems-certs` improve your situation.

**Comment by jxfruit** [comment] 2024-06-03 08:22
@4383 thanks for your reply. I have used the ssl configuration successfully. But we must use the trust ca certification in server side and the browser side, which is not friendly to our clients. So I want to know if we can remove the trusted certification verification in server side with eventlet.

**Comment by 4383** [comment] 2024-06-03 08:40
Concerning the stdlib ssl module, you may have to see:
https://docs.python.org/3/library/ssl.html#ssl.SSLContext.verify_mode

According to the Eventlet doc, the Eventlet's ssl module is built on the top of the PyOpenSSL module, so you may find useful the doc of this lib to see how to disabling the verification, especially the `set_verify(mode, callback)` function and the `VERIFY_NONE` flag:

https://pyopenssl.sourceforge.net/pyOpenSSL.txt

**Comment by 4383** [comment] 2024-06-03 08:41
and the eventlet doc https://eventlet.readthedocs.io/en/latest/ssl.html#using-ssl-with-eventlet

**Comment by jxfruit** [comment] 2024-06-03 10:26
@4383 
thanks for your reply so fast.
yeah, I found the function set_verify, but I have to call with new Context(), and how can I pass this parameter, there is no extra  parameter exposed in eventlet or flask-socketio

**Comment by 4383** [comment] 2024-06-03 12:09
You can't access to the existing context?
I don't think you need extra exposed things on eventlet, as eventlet wrap that lib, so I think you are already able to directly access attributes of that wrapped module.

**Comment by jxfruit** [comment] 2024-06-04 02:33
init_params['cors_allowed_origins'] = '*'
        init_params["allowEIO3"] = True
        # create a Socket.IO server
        app = Flask("robot-server")
        io = SocketIO(app, **init_params)
        namespaceHandler = RobotEngineNamespace(io)
        io.on_namespace(namespaceHandler)
        p_socketio = os.path.dirname(os.path.realpath(__file__))
        p_src = os.path.dirname(p_socketio)  # src
        p_service = os.path.dirname(p_src)  # robot-service-install
        p_service_install = os.path.dirname(p_service)  # robot-service-install
        keyfile_path = os.path.join(os.path.dirname(p_service_install), 'config/key.pem')
        certfile = os.path.join(os.path.dirname(p_service_install), 'config/cert.pem')
        cafile = os.path.join(os.path.dirname(p_service_install), 'config/rootCA.pem')
        kwargs = {
            'keyfile': keyfile_path,  
            'certfile': certfile, 
            'ca_certs': cafile,
            'server_side': True
        }
        io.server.eio.set_verify = SSL.VERIFY_NONE  # set for avoiding verification, but it is useless
        io.run(app, port=port, host=host, debug=False, **kwargs)


with this code, I got a new error:

Traceback (most recent call last):
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/greenthread.py", line 265, in main
    result = function(*args, **kwargs)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 869, in process_request
    proto.__init__(conn_state, self)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 359, in __init__
    self.handle()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 392, in handle
    self.handle_one_request()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 428, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/wsgi.py", line 409, in _read_request_line
    line = self.rfile.readline(self.server.url_length_limit)
  File "/data/app/miniconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 265, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 280, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 196, in read
    return self._call_trampolining(
  File "/data/app/miniconda3/lib/python3.8/site-packages/eventlet/green/ssl.py", line 166, in _call_trampolining
    return func(*a, **kw)
  File "/data/app/miniconda3/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2639)
Removing descriptor: 88

**Comment by 4383** [comment] 2024-06-04 07:28
Are you using a self signed certificat?

**Comment by jxfruit** [comment] 2024-06-04 08:05
@4383 yes, And I tried to use mkcert to generate trusted certification, which got the same error

**Comment by 4383** [comment] 2024-06-04 14:21
So I think Eventlet is not the root causes of your problem...

The error you face means the client does not trust your certificate since it is issued by an unknown entity. If you want to use self-signed certificates you have to explicitly import these as trusted for all clients you want to use.

See this thread https://stackoverflow.com/questions/62518048/python-ssl-socket-server-sslv3-alert-certificate-unknown-issue

Is your code a new code, or an already existing one?
If your code was an existing one, is it previously worked with previous versions of Eventlet?

**Comment by jxfruit** [comment] 2024-06-05 02:25
> So I think Eventlet is not the root causes of your problem...
> 
> The error you face means the client does not trust your certificate since it is issued by an unknown entity. If you want to use self-signed certificates you have to explicitly import these as trusted for all clients you want to use.
> 
> See this thread https://stackoverflow.com/questions/62518048/python-ssl-socket-server-sslv3-alert-certificate-unknown-issue
> 
> Is your code a new code, or an already existing one? If your code was an existing one, is it previously worked with previous versions of Eventlet?

yes, Eventlet is not the root causes of my problem. I am just looking forward a solution.
It is the new code, I quit finally. I have to force clients to install our ca certification.
Anyway, thanks for all your fast response, glod bless

**Comment by 4383** [comment] 2024-06-05 10:30
No problem.
I'd add one final advice before closing this issue.

Eventlet is deprecated and we will lead it to the abandon.
As this is a new code, instead of using Eventlet and flask-socketio, I'd rather suggest you to use an Asyncio based approach, like [aiohttp](https://docs.aiohttp.org/en/stable/index.html).

This lib is awesome, and you may find it useful.

**Closed** 2024-06-05 10:30 UTC
