### ISSUE TITLE
HTTPS/SSL failure when using requests library on Python 3.4

### ISSUE THREAD

**Issue by mkai** [eventlet/eventlet#226] opened 2015-04-11 11:31 UTC
I use Python 3.4.3. HTTPS requests using the requests library normally work fine:

```python
>>> import requests
>>> requests.get('https://www.github.com/').status_code
200
```

However, if eventlet is imported, I get the following error:

```python
>>> import eventlet
>>> import requests
>>> requests.get('https://www.github.com/').status_code
venv/lib/python3.4/site-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.4/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "venv/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "venv/lib/python3.4/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "venv/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "venv/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "venv/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
    match_hostname(cert, self.assert_hostname or hostname)
  File ".pyenv/versions/3.4.3/lib/python3.4/ssl.py", line 261, in match_hostname
    raise ValueError("empty or no certificate, match_hostname needs a "
ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```

I read about bugfixes to the SSL wrapping on Python >= 2.7.9. Is this related?

**Comment by temoto** [comment] 2015-04-11 18:08
Just importing eventlet should not change anything. Anyway the error you observe does not look like it's related to SSL fixes. To investigate deeper, please, post
```
uname -a
python -V
pip freeze
```

**Comment by mkai** [comment] 2015-04-11 19:51
I can reproduce the error using the following steps:

```bash
$ mkdir app
$ cd app/
app $ python -m venv venv
app $ source venv/bin/activate
(venv) app $ python -V
Python 3.4.3

(venv) app $ pip install requests eventlet
Collecting requests
  Using cached requests-2.6.0-py2.py3-none-any.whl
Collecting eventlet
  Using cached eventlet-0.17.3-py2.py3-none-any.whl
Collecting greenlet>=0.3 (from eventlet)
  Using cached greenlet-0.4.5.zip
Installing collected packages: greenlet, eventlet, requests
  Running setup.py install for greenlet
    building 'greenlet' extension
    clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iapp/venv/include -I.pyenv/versions/3.4.3/include/python3.4m -c greenlet.c -o build/temp.macosx-10.10-x86_64-3.4/greenlet.o
    clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L.pyenv/versions/3.4.3/lib build/temp.macosx-10.10-x86_64-3.4/greenlet.o -o build/lib.macosx-10.10-x86_64-3.4/greenlet.so


Successfully installed eventlet-0.17.3 greenlet-0.4.5 requests-2.6.0

(venv) app $ python
Python 3.4.3 (default, Mar 20 2015, 17:27:39)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://www.github.com/').status_code
200
>>> ^D

(venv) app $ python
Python 3.4.3 (default, Mar 20 2015, 17:27:39)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> import requests
>>> requests.get('https://www.github.com/').status_code
app/venv/lib/python3.4/site-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "app/venv/lib/python3.4/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "app/venv/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "app/venv/lib/python3.4/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "app/venv/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "app/venv/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "app/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "app/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "app/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "app/venv/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
    match_hostname(cert, self.assert_hostname or hostname)
  File ".pyenv/versions/3.4.3/lib/python3.4/ssl.py", line 261, in match_hostname
    raise ValueError("empty or no certificate, match_hostname needs a "
ValueError: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED
>>> ^D

(venv) app $ uname -a
Darwin 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

(venv) app $ python -V
Python 3.4.3

(venv) app $ pip freeze
eventlet==0.17.3
greenlet==0.4.5
requests==2.6.0
(venv) app $

```

Hope that helps.

**Comment by temoto** [comment] 2015-04-11 23:56
Yup, it reproduces on my machine. Counter intuitive stuff. Thanks for report. I'll fix it soon.

**Comment by samstav** [comment] 2015-04-16 15:39
I can confirm that this happens in python 2.7.9 as well, which uses 3.4's ssl module backported.

**Comment by jstasiak** [comment] 2015-04-16 21:39
I can confirm it happening on CPython 2.7.9, seems to be introduced by https://github.com/eventlet/eventlet/commit/b2e5146dec8f6fe075884dcf788f64a16bc3fec3

**Comment by temoto** [comment] 2015-05-02 03:02
Fixed in master a07f836 , thanks to @stuart-mclaren

**Closed by temoto** 2015-05-02 03:02 UTC
Labels: bug, python3

**Comment by meunierd** [comment] 2015-05-25 13:37
There are still issues around SSL and requests with eventlet 0.17.4:

Steps to reproduce:

    import eventlet
    eventlet.monkey_patch()
    import requests
    requests.get('https://google.com')
    Traceback (most recent call last):
      File "/Users/devonmeunier/.env/flux/lib/python3.4/site-packages/eventlet/hubs/hub.py", line 457, in fire_timers
        timer()
      File "/Users/devonmeunier/.env/flux/lib/python3.4/site-packages/eventlet/hubs/timer.py", line 58, in __call__
        cb(*args, **kw)
      File "/Users/devonmeunier/.env/flux/lib/python3.4/site-packages/eventlet/semaphore.py", line 145, in _do_acquire
        waiter.switch()
    greenlet.error: cannot switch to a different thread
    >>> <Response [200]>
    eventlet.__version__
    >>> '0.17.4'
    requests.__version__
    >>> '2.4.3'

**Comment by stuart-mclaren** [comment] 2015-05-28 10:39
I don't see the greenlet error with a later version of requests (2.7.0)

$ python
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eventlet
>>> eventlet.monkey_patch()
>>> import requests
>>> requests.get('https://google.com')
<Response [200]>
>>> eventlet.__version__
'0.17.4'
>>> requests.__version__
'2.7.0'

**Comment by uddraut** [comment] 2023-03-12 14:51
Error info: empty or no certificate, match_hostname needs a SSL socket or SSL context with either CERT_OPTIONAL or CERT_REQUIRED

Please help me

**Comment by temoto** [comment] 2023-03-19 00:08
@uddraut are you using Python 3.4?
