### ISSUE TITLE
eventlet hanging

### ISSUE THREAD

**Issue by shivaenigma** [eventlet/eventlet#157] opened 2014-10-30 12:09 UTC
Hi, 
We are using multiple greenthreads  that fetch ssl urls , and on ocassions the whole process hangs.  
Due to this our server is hanging on random intervals . FYI: Using eventlet 0.15.2 on python 3.4.0
```
(gdb) info threads
  Id   Target Id         Frame 
  4    Thread 0x7f726668c700 (LWP 25924) "python3" 0x00007f726c04e3bd in read ()
    at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7f7265c8b700 (LWP 25925) "python3" 0x00007f726bd6b8e3 in select ()
    at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7f726528a700 (LWP 25926) "python3" 0x00007f726bd74653 in epoll_wait ()
    at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7f726c473740 (LWP 25900) "python3" 0x00007f726c04e3bd in read ()
    at ../sysdeps/unix/syscall-template.S:81
```
```
(gdb) bt
#0  0x00007f726c04e3bd in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f726990f72b in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007f726990d74b in BIO_read () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007f7269c315fb in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#4  0x00007f7269c3072a in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#5  0x00007f7269e72999 in PySSL_SSLdo_handshake.4031 (self=0x7f72646f1688)
    at /build/buildd/python3.4-3.4.0/Modules/_ssl.c:568
#6  0x000000000057c278 in call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at ../Python/ceval.c:4210
#7  PyEval_EvalFrameEx (f=f@entry=0x2ed9908, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#8  0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726a08c9c0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kws=0x2ed1a40, 
    kwcount=kwcount@entry=0, defs=0x7f726a0b1d48, defcount=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#9  0x000000000057bfaa in fast_function (nk=0, na=1, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726a0b0488) at ../Python/ceval.c:4334
#10 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#11 PyEval_EvalFrameEx (f=f@entry=0x2ed1818, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#12 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726a087ae0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=args@entry=0x7f7264869e28, argcount=1, 
    kws=kws@entry=0x7f72667ca210, kwcount=kwcount@entry=6, defs=defs@entry=0x7f726a354848, 
    defcount=defcount@entry=17, kwdefs=0x0, closure=0x0) at ../Python/ceval.c:3578
#13 0x000000000057e0eb in function_call.80987 (func=0x7f726a0af620, arg=0x7f7264869e10, 
    kw=0x7f7266757d48) at ../Objects/funcobject.c:632
#14 0x000000000043810a in PyObject_Call (func=func@entry=0x7f726a0af620, 
    arg=arg@entry=0x7f7264869e10, kw=kw@entry=0x7f7266757d48) at ../Objects/abstract.c:2067
#15 0x00000000004d3745 in method_call.76941 (func=0x7f726a0af620, arg=0x7f7264869e10, 
    kw=0x7f7266757d48) at ../Objects/classobject.c:347
#16 0x000000000043810a in PyObject_Call (func=func@entry=0x7f72646b6e08, 
    arg=arg@entry=0x7f726c2a3048, kw=kw@entry=0x7f7266757d48) at ../Objects/abstract.c:2067
#17 0x00000000004ab81b in slot_tp_init.16919 (self=0x7f72667044c0, args=0x7f726c2a3048, 
    kwds=0x7f7266757d48) at ../Objects/typeobject.c:6023
#18 0x000000000047a7aa in type_call.16630 (type=<optimized out>, args=0x7f726c2a3048, 
    kwds=0x7f7266757d48) at ../Objects/typeobject.c:869
#19 0x000000000043810a in PyObject_Call (func=func@entry=0x2b364d8, 
    arg=arg@entry=0x7f726c2a3048, kw=kw@entry=0x7f7266757d48) at ../Objects/abstract.c:2067
#20 0x0000000000579f45 in do_call (nk=<optimized out>, na=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x2b364d8) at ../Python/ceval.c:4456
#21 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4254
#22 PyEval_EvalFrameEx (f=f@entry=0x2f93448, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#23 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726a0876f0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kws=0x2fd5f88, 
    kwcount=kwcount@entry=1, defs=0x7f72697f8420, defcount=4, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#24 0x000000000057bfaa in fast_function (nk=1, na=2, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726a0af2f0) at ../Python/ceval.c:4334
#25 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#26 PyEval_EvalFrameEx (f=f@entry=0x2fd5de8, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#27 0x000000000057c0db in fast_function (nk=<optimized out>, na=1, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868c510) at ../Python/ceval.c:4324
#28 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#29 PyEval_EvalFrameEx (f=f@entry=0x2fd5b78, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#30 0x000000000057c0db in fast_function (nk=<optimized out>, na=2, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868aea0) at ../Python/ceval.c:4324
#31 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#32 PyEval_EvalFrameEx (f=f@entry=0x7f72647b73d8, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#33 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f7268683c00, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, 
    kws=0x7f72667b4708, kwcount=kwcount@entry=0, defs=0x7f72686895a0, defcount=1, kwdefs=0x0, 
    closure=0x0) at ../Python/ceval.c:3578
#34 0x000000000057bfaa in fast_function (nk=0, na=2, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868c048) at ../Python/ceval.c:4334
#35 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#36 PyEval_EvalFrameEx (f=f@entry=0x7f72667b4570, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#37 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f7268683e40, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kws=0x2fd5b38, 
    kwcount=kwcount@entry=0, defs=0x7f7268689728, defcount=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#38 0x000000000057bfaa in fast_function (nk=0, na=2, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868c1e0) at ../Python/ceval.c:4334
#39 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#40 PyEval_EvalFrameEx (f=f@entry=0x2fd5968, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#41 0x000000000057c0db in fast_function (nk=<optimized out>, na=5, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868c378) at ../Python/ceval.c:4324
#42 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#43 PyEval_EvalFrameEx (f=f@entry=0x7f7266789048, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#44 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f7268683ed0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=5, kws=0x2fd4b80, 
    kwcount=kwcount@entry=0, defs=0x7f72686643e0, defcount=2, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#45 0x000000000057bfaa in fast_function (nk=0, na=5, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726868c268) at ../Python/ceval.c:4334
#46 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#47 PyEval_EvalFrameEx (f=f@entry=0x2fd4988, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#48 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f7268626e40, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, 
    kws=0x7f72667845a8, kwcount=kwcount@entry=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#49 0x000000000057bfaa in fast_function (nk=2, na=3, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863dc80) at ../Python/ceval.c:4334
#50 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#51 PyEval_EvalFrameEx (f=f@entry=0x7f7266784408, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#52 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726862b150, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=2, kws=kws@entry=0x0, 
    kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=0x0, 
    closure=0x0) at ../Python/ceval.c:3578
#53 0x000000000057df80 in function_call.80987 (func=0x7f726863de18, arg=<optimized out>, 
    kw=<optimized out>) at ../Objects/funcobject.c:632
#54 0x000000000043810a in PyObject_Call (func=func@entry=0x7f726863de18, 
    arg=arg@entry=0x7f72646b6a08, kw=kw@entry=0x0) at ../Objects/abstract.c:2067
#55 0x0000000000579616 in ext_do_call (nk=<optimized out>, na=1, flags=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863de18) at ../Python/ceval.c:4551
#56 PyEval_EvalFrameEx (f=f@entry=0x7f72666ba048, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2869
#57 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c8a0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=5, 
    kws=0x7f7266789b98, kwcount=kwcount@entry=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#58 0x000000000057bfaa in fast_function (nk=0, na=5, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b6a8) at ../Python/ceval.c:4334
#59 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#60 PyEval_EvalFrameEx (f=f@entry=0x7f72667899d0, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829

#61 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c9c0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kws=0x2fd4958, 
    kwcount=kwcount@entry=0, defs=0x7f7268636798, defcount=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#62 0x000000000057bfaa in fast_function (nk=0, na=3, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b7b8) at ../Python/ceval.c:4334
#63 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#64 PyEval_EvalFrameEx (f=f@entry=0x2fd4778, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#65 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c930, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kws=0x2fd4728, 
    kwcount=kwcount@entry=0, defs=0x7f726862ce20, defcount=2, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#66 0x000000000057bfaa in fast_function (nk=0, na=4, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b730) at ../Python/ceval.c:4334
#67 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#68 PyEval_EvalFrameEx (f=f@entry=0x2fd4548, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#69 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726867f4b0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kws=0x2f6aa40, 
    kwcount=kwcount@entry=0, defs=0x7f726865c9e0, defcount=2, kwdefs=0x7f7268681448, closure=0x0)
    at ../Python/ceval.c:3578
#70 0x000000000057bfaa in fast_function (nk=0, na=1, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f72686257b8) at ../Python/ceval.c:4334
#71 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#72 PyEval_EvalFrameEx (f=f@entry=0x2f6a878, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#73 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f72686728a0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kws=0x2fbabc0, 
    kwcount=kwcount@entry=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#61 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c9c0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kws=0x2fd4958, 
    kwcount=kwcount@entry=0, defs=0x7f7268636798, defcount=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#62 0x000000000057bfaa in fast_function (nk=0, na=3, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b7b8) at ../Python/ceval.c:4334
#63 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#64 PyEval_EvalFrameEx (f=f@entry=0x2fd4778, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#65 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c930, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kws=0x2fd4728, 
    kwcount=kwcount@entry=0, defs=0x7f726862ce20, defcount=2, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#66 0x000000000057bfaa in fast_function (nk=0, na=4, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b730) at ../Python/ceval.c:4334
#67 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#68 PyEval_EvalFrameEx (f=f@entry=0x2fd4548, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#69 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726867f4b0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kws=0x2f6aa40, 
    kwcount=kwcount@entry=0, defs=0x7f726865c9e0, defcount=2, kwdefs=0x7f7268681448, closure=0x0)
    at ../Python/ceval.c:3578
#70 0x000000000057bfaa in fast_function (nk=0, na=1, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f72686257b8) at ../Python/ceval.c:4334
#71 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#72 PyEval_EvalFrameEx (f=f@entry=0x2f6a878, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#73 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f72686728a0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kws=0x2fbabc0, 
    kwcount=kwcount@entry=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#61 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c9c0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kws=0x2fd4958, 
    kwcount=kwcount@entry=0, defs=0x7f7268636798, defcount=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#62 0x000000000057bfaa in fast_function (nk=0, na=3, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b7b8) at ../Python/ceval.c:4334
#63 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#64 PyEval_EvalFrameEx (f=f@entry=0x2fd4778, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#65 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726861c930, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kws=0x2fd4728, 
    kwcount=kwcount@entry=0, defs=0x7f726862ce20, defcount=2, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#66 0x000000000057bfaa in fast_function (nk=0, na=4, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726863b730) at ../Python/ceval.c:4334
#67 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#68 PyEval_EvalFrameEx (f=f@entry=0x2fd4548, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#69 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726867f4b0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kws=0x2f6aa40, 
    kwcount=kwcount@entry=0, defs=0x7f726865c9e0, defcount=2, kwdefs=0x7f7268681448, closure=0x0)
    at ../Python/ceval.c:3578
#70 0x000000000057bfaa in fast_function (nk=0, na=1, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f72686257b8) at ../Python/ceval.c:4334
#71 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#72 PyEval_EvalFrameEx (f=f@entry=0x2f6a878, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#73 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f72686728a0, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kws=0x2fbabc0, 
    kwcount=kwcount@entry=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#74 0x000000000057bfaa in fast_function (nk=0, na=2, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f7268647ae8) at ../Python/ceval.c:4334
#75 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#76 PyEval_EvalFrameEx (f=f@entry=0x2fba9d8, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#77 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f7268d9c810, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=0, 
    kws=0x7f72647f2738, kwcount=kwcount@entry=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#78 0x000000000057bfaa in fast_function (nk=1, na=0, n=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f7268d55730) at ../Python/ceval.c:4334
#79 call_function (oparg=<optimized out>, pp_stack=<synthetic pointer>) at ../Python/ceval.c:4252
#80 PyEval_EvalFrameEx (f=f@entry=0x7f72647f25a0, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#81 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726afbc150, globals=<optimized out>, 
    locals=locals@entry=0x0, args=<optimized out>, argcount=2, kws=kws@entry=0x0, 
    kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=0x0, 
    closure=0x0) at ../Python/ceval.c:3578
#82 0x000000000057df80 in function_call.80987 (func=0x7f7266e0fc80, arg=<optimized out>, 
    kw=<optimized out>) at ../Objects/funcobject.c:632
#83 0x000000000043810a in PyObject_Call (func=func@entry=0x7f7266e0fc80, 
    arg=arg@entry=0x7f72646ace08, kw=kw@entry=0x0) at ../Objects/abstract.c:2067
#84 0x0000000000579616 in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f7266e0fc80) at ../Python/ceval.c:4551
#85 PyEval_EvalFrameEx (f=f@entry=0x7f72647fd648, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2869
#86 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726b038f60, globals=<optimized out>, 
    locals=locals@entry=0x0, args=args@entry=0x7f72667c0ae0, argcount=2, 
    kws=kws@entry=0x7f726c2a3060, kwcount=kwcount@entry=0, defs=defs@entry=0x0, 
    defcount=defcount@entry=0, kwdefs=0x0, closure=0x7f72648671d0) at ../Python/ceval.c:3578
#87 0x000000000057e0eb in function_call.80987 (func=0x7f726671e1e0, arg=0x7f72667c0ac8, 
    kws=kws@entry=0x7f726c2a3060, kwcount=kwcount@entry=0, defs=defs@entry=0x0, 
    defcount=defcount@entry=0, kwdefs=0x0, closure=0x7f72648671d0) at ../Python/ceval.c:3578
#87 0x000000000057e0eb in function_call.80987 (func=0x7f726671e1e0, arg=0x7f72667c0ac8, 
---Type <return> to continue, or q <return> to quit---
    kw=0x7f7264704a48) at ../Objects/funcobject.c:632
#88 0x000000000043810a in PyObject_Call (func=func@entry=0x7f726671e1e0, 
    arg=arg@entry=0x7f72667c0ac8, kw=kw@entry=0x7f7264704a48) at ../Objects/abstract.c:2067
#89 0x0000000000579616 in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, 
    pp_stack=<synthetic pointer>, func=0x7f726671e1e0) at ../Python/ceval.c:4551
#90 PyEval_EvalFrameEx (f=f@entry=0x2fba778, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2869
#91 0x000000000057d3d3 in PyEval_EvalCodeEx (_co=0x7f726a32a810, globals=<optimized out>, 
    locals=locals@entry=0x0, args=args@entry=0x7f7264788270, argcount=5, 
    kws=kws@entry=0x7f726c2a3060, kwcount=kwcount@entry=0, defs=defs@entry=0x0, 
    defcount=defcount@entry=0, kwdefs=0x0, closure=0x0) at ../Python/ceval.c:3578
#92 0x000000000057e0eb in function_call.80987 (func=0x7f726a0c3c80, arg=0x7f7264788258, 
    kw=0x7f7266721848) at ../Objects/funcobject.c:632
#93 0x000000000043810a in PyObject_Call (func=func@entry=0x7f726a0c3c80, 
    arg=arg@entry=0x7f7264788258, kw=kw@entry=0x7f7266721848) at ../Objects/abstract.c:2067
#94 0x00000000004d3745 in method_call.76941 (func=0x7f726a0c3c80, arg=0x7f7264788258, 
    kw=0x7f7266721848) at ../Objects/classobject.c:347
#95 0x000000000043810a in PyObject_Call (func=0x7f726674e588, arg=arg@entry=0x7f726480db38, 
    kw=<optimized out>) at ../Objects/abstract.c:2067
#96 0x00000000004d3360 in PyEval_CallObjectWithKeywords (func=func@entry=0x7f726674e588, 
    arg=arg@entry=0x7f726480db38, kw=kw@entry=0x7f7266721848) at ../Python/ceval.c:4104
#97 0x00007f726ad335c8 in g_initialstub (mark=mark@entry=0x7fff209dc928) at greenlet.c:788
#98 0x00007f726ad32f56 in g_switch (target=0x7f7266791048, args=0x7f726480db38, 
    kwargs=<optimized out>) at greenlet.c:560
#99 0x00007f726a0c8390 in ?? ()
#100 0x00007f7266e28808 in ?? ()
#101 0x0000000000000000 in ?? ()
```

**Comment by temoto** [comment] 2015-04-03 03:06
@shivaenigma could you try recent master or v0.17.2 and say if the problem was fixed or not?

**Comment by jstasiak** [comment] 2015-11-08 20:13
@shivaenigma Have you tested with the newest Eventlet yet?

**Comment by jstasiak** [comment] 2015-11-22 21:58
To the best of my knowledge this issue is fixed by the commits references above - I'm tempted to close this issue and only reopen if this is confirmed to still be an issue with the latest stable version.

**Closed** 2015-11-25 11:25 UTC
Labels: bug, need-contributor, need-test, python3
