### ISSUE TITLE
Asyncio hub doesn't clean up bad file descriptors

### ISSUE THREAD

**Issue by itamarst** [eventlet/eventlet#927] opened 2024-03-07 14:53 UTC
Moreover, there appear to be no tests for this implicit behavior, or it would've been caught.

The motivation is #912. A previous attempt was #924.

**Comment by itamarst** [comment] 2024-03-07 15:37
@4383 Insofar as this is a behavior difference in the asyncio hub, it's _very_ subtle and I still think the issue in in wsgi.py. I noticed that the `accept()` was rising an EINVAL error but that isn't anywhere in the code base so not sure how it went from EBADF to EINVAL...

**Comment by itamarst** [comment] 2024-03-07 16:49
Would welcome ideas on how to reproduce a behavioral difference, but at the moment I'm giving up on this since the obvious case has the same behavior.

**Comment by 4383** [comment] 2024-03-08 13:11
> My initial test suggests that this only works for non-asyncio hubs by accident, in the specific test edge case? In particular, consider the following:
> 
> ```python
> import eventlet
> import eventlet.hubs
> eventlet.monkey_patch()
> print(eventlet.hubs.get_hub())
> 
> sock = eventlet.listen(("127.0.0.1", 0))
> print(sock)
> eventlet.sleep(0.0001)
> sock.close()
> for i in range(3):
>     try:
>         sock.accept()
>     except Exception as e:
>         print(e)
> ```
> 
> When run:
> 
> ```
> $ EVENTLET_HUB=asyncio python 912.py 
> <eventlet.hubs.asyncio.Hub object at 0x7393cd78dcd0>
> <eventlet.greenio.base.GreenSocket object at 0x7393cc1d8650>
> [Errno 9] Bad file descriptor
> [Errno 9] Bad file descriptor
> [Errno 9] Bad file descriptor
> 
> 
> $ EVENTLET_HUB=epolls python 912.py 
> <eventlet.hubs.epolls.Hub object at 0x7fc2c073b150>
> <eventlet.greenio.base.GreenSocket object at 0x7fc2bf7920d0>
> [Errno 9] Bad file descriptor
> [Errno 9] Bad file descriptor
> [Errno 9] Bad file descriptor
> ```

The scenario for #912 is a bit different, the listening socket is given to a wsgi server, and this is this wsgi server who handle/hide the EBADF use case, see:

https://github.com/eventlet/eventlet/pull/912/files#diff-16136b55b4c371bb0a3e14aa85bbeba8a91adab2c6fb7b7261b67f5a92cba8d0R2001-R2018

In your example you use a convenience that return you a "raw" socket without fault tolerance management implemented by eventlet.

https://github.com/eventlet/eventlet/blob/master/eventlet/convenience.py#L34 

But, yes, I agree, the issue is in the wsgi module. EBADF should be managed in different way in the wsgi server. That would allow to remove all these tricky logic implemented on the hubs side, and then, avoiding us to something like the one I proposed with #924.

- https://github.com/eventlet/eventlet/blob/master/eventlet/hubs/poll.py#L71
- https://github.com/eventlet/eventlet/blob/master/eventlet/hubs/selects.py#L31
- etc...

Thinking out loud, an other potential optimization could be to use the weakref module to manage readers and writers at the hub level, hence, if a socket is closed/terminated/whatevered, it would automatically removed from these lists (reader, writer). Avoiding us implementing additional logical to remove file descriptors as already made in hubs.

Thoughts?

**Comment by 4383** [comment] 2024-03-08 13:21
I'd suggest:

1) removing `EBADF` from from accept errno in the wsgi module (https://github.com/eventlet/eventlet/blob/master/eventlet/wsgi.py#L882);
2) properly handle the shutdown of the impacted wsgi server and logging errors and details to user, and avoid crashing all the user process if the wsgi server is broken;
3) using weakref to manage hub listeners.

Thoughts?

**Comment by itamarst** [comment] 2024-03-08 13:23
I already did the first item in #912. For the rest, I will get back to this next week when hopefully I will be feeling better.

**Comment by 4383** [comment] 2024-03-08 14:01
Oh take care!

**Comment by 4383** [comment] 2024-03-08 14:07
Indeed sorry, I missed you pushed a new commit on #912. Thank you.

**Comment by 4383** [comment] 2024-03-13 09:37
I think we can close this issue.

I started some local refactor to try to implement the listeners logic by using the weakref module (WeakValueDictionary).
The key is the file descriptor number, and the value is the file descriptor itself. If the file descriptor is deleted (out of scope, moved to garbage collector, etc), then the entry in the dictionary will be automatically removed.

It would avoid all these removal dances, and I think that it could improve performance a bit.

**Closed by 4383** 2024-03-13 09:37 UTC
