### ISSUE TITLE
subprocess.TimeoutExpired used in test suite doesnt exist on py27

### ISSUE THREAD

**Issue by jayvdb** [eventlet/eventlet#641] opened 2020-08-18 05:10 UTC
`tests/__init__.py` includes
```py
        try:
            output, _ = p.communicate(timeout=timeout)
       except subprocess.TimeoutExpired:
           ...
```

However `communicate(timeout)` and `subprocess.TimeoutExpired` were only introduced in py33

**Comment by temoto** [comment] 2020-08-19 10:59
Duplicate of #342 
> We already use subprocess32 compatibility layer for that:
> 
> ```
> # tests/__init__
> try:
>     import subprocess32 as subprocess  # py2
> except ImportError:
>     import subprocess  # py3
> 
> # tox.ini
> deps =
>     py{26,27}: subprocess32==3.2.7
> ```
> 
> Run tests in one of tox defined environments, or install `subprocess32` explicitly.

**Closed by temoto** 2020-08-19 10:59 UTC

**Comment by temoto** [comment] 2020-08-19 11:02
Also, one of issue or PR is enough.
