### ISSUE TITLE
RuntimeWarning when using eventlet for patching requests

### ISSUE THREAD

**Issue by imazor** [eventlet/eventlet#208] opened 2015-03-03 16:08 UTC
Hi,
I am getting the following warning while using requests with eventlet:
`/usr/local/lib/python2.7/site-packages/requests/utils.py:74: RuntimeWarning: Parent module 'requests' not found while handling absolute import from netrc import netrc, NetrcParseError`

this is my use for the patching:
import eventlet
Monkey-patch.
requests = eventlet.patcher.import_patched('requests')

Export same items as vanilla requests
```
__requests_imports__ = ['utils', 'session', 'Session', 'codes', 'RequestException', 'Timeout', 'URLRequired',
                        'TooManyRedirects', 'HTTPError', 'ConnectionError']
eventlet.patcher.slurp_properties(requests, globals(), srckeys=__requests_imports__)
```
I took this from:
https://github.com/saghul/erequests

Is it ok? can I ignore it? Have I done something wrong?

**Comment by temoto** [comment] 2015-03-03 16:23
Could you try `import_patched('requests.__init__')` ?

**Comment by imazor** [comment] 2015-03-04 08:47
Looks like it solves the issue.

Thanks.

On Tue, Mar 3, 2015 at 5:23 PM, Sergey Shepelev <notifications@github.com>
wrote:

> Could you try import_patched('requests.__init__') ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventlet/eventlet/issues/208#issuecomment-76978478>.
>



-- 
*--------------------------------------------------------------------------*

*Igor Mazor*
Senior Data Engineer


Rocket Internet AG  |  Johannisstraße 20  |  10117 Berlin  |  Deutschland
skype: igor_rocket_internet | mail: igor.mazor <http://goog_862328191>
@rocket-internet.de
www.rocket-internet.de

Geschäftsführer: Dr. Johannes Bruder, Arnt Jeschke, Alexander Kudlich
Eingetragen beim Amtsgericht Berlin, HRB 109262 USt-ID DE256469659

**Comment by temoto** [comment] 2015-03-04 10:19
Note: this issue is fixed when `import_patched` does this `__init__` trick automatically.

**Comment by temoto** [comment] 2015-03-04 10:20
Closing as duplicate of #7 then. Thanks for providing more info how to reproduce it.

**Closed by temoto** 2015-03-04 10:20 UTC

**Comment by maxkoryukov** [comment] 2018-04-23 03:28
As mentioned above, the problem is in the `eventlet` library.

Here is an original tip (by @temoto) how to solve the problem: https://github.com/eventlet/eventlet/issues/208#issuecomment-76978478

And this is my workaround:

```python
from eventlet import import_patched
requests = import_patched('requests.__init__')
```

## see also

* https://github.com/requests/requests/issues/2469
* https://github.com/requests/requests/issues/2014
