### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by shivaenigma** [eventlet/eventlet#145] opened 2014-10-10 15:39 UTC
I am using latest git code from python3.3 branch on ubuntu. Let me know if you need any more information

```
  File "/usr/lib/python3.4/urllib/request.py", line 1232, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1205, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 578, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)
```

**Comment by temoto** [comment] 2015-02-13 09:43
@jstasiak please comment if this issue is supposed to be fixed with #199 merged?

**Comment by jstasiak** [comment] 2015-02-13 18:04
To the best of my knowledge, yes.

**Comment by temoto** [comment] 2015-02-13 20:36
@shivaenigma please, try again with recent master.

**Comment by bitnumus** [comment] 2015-02-15 09:07
@temoto I will test it this week and let you know

**Comment by bitnumus** [comment] 2015-02-26 13:19
@temoto I'm now receiving an import error for urllib, what changed? i opened an issue regarding this also.

**Comment by bitnumus** [comment] 2015-02-26 16:52
@temoto recent master seems to have broken our current code due to import errors with urlopen, so i'll have to fix this and take another look.

However, i wrote another script to test "requests" lib with eventlet and if i try to use a full poll of 1000 requests i get the same error as in this issue. Is it likely there will be full support for requests library in the future rather than through monkey_patch() or however its working at the moment? urllib imho really is an awful library to develop with, requests just seems far cleaner.

**Comment by temoto** [comment] 2015-02-26 17:00
@bitnumus do you mean "ssl.SSLEOFError: EOF occurred in violation of protocol" ? Can you show the code?

**Comment by bitnumus** [comment] 2015-02-27 15:03
@temoto Yes thats the same error. I quickly wrote a script to find valid google picasa profiles that replicates the issue for me. Things run fine then all of a sudden it will spit out tons of tracebacks all with the resulting final line:

urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:598)

http://pastebin.com/NnTpakmm

**Comment by jstasiak** [comment] 2015-11-08 20:19
@shivaenigma With Python 3.5.0 and Eventlet 0.17.4 I'm unable to reproduce this, can you confirm whether this is still an issue?

**Closed as completed** 2021-12-09 22:10 UTC
Labels: importance-bug, platform-python3, need-feedback
