### ISSUE TITLE
Eventlet Python 12.0 issue

### ISSUE THREAD

**Issue by DrDumbenstein** [eventlet/eventlet#812] opened 2023-10-04 01:44 UTC
(CarSim) C:\Users\Seddik\OneDrive\Desktop\CARSIM>python drive.py
Traceback (most recent call last):
  File "C:\Users\Seddik\OneDrive\Desktop\CARSIM\drive.py", line 8, in <module>
    import eventlet
  File "D:\anaconda3\envs\CarSim\Lib\site-packages\eventlet\__init__.py", line 17, in <module>
    from eventlet import convenience
  File "D:\anaconda3\envs\CarSim\Lib\site-packages\eventlet\convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "D:\anaconda3\envs\CarSim\Lib\site-packages\eventlet\green\socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "D:\anaconda3\envs\CarSim\Lib\site-packages\eventlet\support\greendns.py", line 45, in <module>
    from eventlet.green import ssl
  File "D:\anaconda3\envs\CarSim\Lib\site-packages\eventlet\green\ssl.py", line 25, in <module>
    _original_wrap_socket = __ssl.wrap_socket
                            ^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Comment by fruch** [comment] 2023-10-11 16:16
can confirm seeing as well in 
https://github.com/scylladb/python-driver/pull/260

**Comment by osfrickler** [comment] 2023-10-27 13:58
duplicate of https://github.com/eventlet/eventlet/issues/795

**Comment by 4383** [comment] 2023-12-15 08:53
Indeed, this is a duplication of #795 let's track discussion over #795.
Closing this issue to reduce the backlog.

Thanks for raising up our attention.

**Closed by 4383** 2023-12-15 08:53 UTC
