### ISSUE TITLE
ipv6 patch breaks dnspython reverse.from_address function

### ISSUE THREAD

**Issue by ekarlso** [eventlet/eventlet#203] opened 2015-02-23 12:56 UTC
I suspect https://github.com/eventlet/eventlet/commit/a6ce444265d36fb23361809d40da73caf4864487 is the culprit.

I have verified that before the commit it works fine before the commit.

Example:
```
import eventlet
from dns import reversename

eventlet.monkey_patch(all=True)

reversename.from_address("10.0.0.1")


Exception:
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    reversename.from_address("10.0.0.1")
  File "/home/karlsone/projects/dnsaas/designate/.venv/local/lib/python2.7/site-packages/dns/reversename.py", line 46, in from_address
    return dns.name.from_text('.'.join(parts), origin=origin)
  File "/home/karlsone/projects/dnsaas/designate/.venv/local/lib/python2.7/site-packages/dns/name.py", line 607, in from_text
    raise ValueError("origin must be a Name or None")
ValueError: origin must be a Name or None
```

**Comment by kiall** [comment] 2015-02-23 12:57
Downstream bug against OpenStack Designate - https://bugs.launchpad.net/designate/+bug/1424621

**Comment by ekarlso** [comment] 2015-02-23 13:05
https://bitbucket.org/eventlet/eventlet/issue/169/ipv6-patch-breaks-dnspython < bb bug

**Comment by temoto** [comment] 2015-02-23 14:22
Thank you, bugfix release is coming soon.

**Comment by kiall** [comment] 2015-02-24 11:04
Hey @temoto - Any luck finding the root cause? I've dug about as far into it as I can given my lack of experience with eventlet's codebase, and came up empty ;)

**Comment by temoto** [comment] 2015-02-24 11:14
@kiall not yet, debugging

**Comment by temoto** [comment] 2015-02-24 13:58
The problem is in patching `dns.name.Name`. Fix will be released today.

**Comment by temoto** [comment] 2015-02-25 03:36
v0.17.1 with this bug fixed is out on PyPi. Thanks for reporting.

**Closed by temoto** 2015-02-25 03:36 UTC

**Comment by kiall** [comment] 2015-02-25 18:16
Thanks :) Sadly, the fixed version has highlighted other issues in our code / tests .. Whoops! Either way, the original issue does seem to be fixed and I suspect the remaining issues are all ours to fix.. Thanks!
