### ISSUE TITLE
Keep-alive WSGI server connections prevent shutdown

### ISSUE THREAD

**Issue by markgoddard** [eventlet/eventlet#188] opened 2015-01-08 11:31 UTC
In the eventlet.wsgi module, following the https://github.com/eventlet/eventlet/commit/1c30e9b39f4330babcb3665df4c1a3ba694bc6c1 changeset, the WSGI server function always waits for all threads to terminate before returning.

This was a useful change as it ensures a more graceful cleanup (although might have undesirable effects when used with the custom_pool parameter). However, if the server supports keepalive connections, these will cause the GreenPool.waitall() call to hang until all connections have terminated.

There ought to be some mechanism to ensure that in progress requests are serviced and cleanly disconnected, but that persistent connections are 'snipped' between requests. The appropriate point at which to split this is https://github.com/eventlet/eventlet/blob/master/eventlet/wsgi.py#L276 (as connections may already be waiting).

Possible solution (based on little experience with eventlet) might take the form of a eventlet.green.select over self.rfile and a GreenPipe passed in from the server. The GreenPipe could be signalled on shutdown by the server, triggering the connection to wake up and disconnect.

**Comment by markgoddard** [comment] 2015-01-08 11:32
See https://bugs.launchpad.net/keystone/+bug/1408612 for an instance of this in the wild.

**Comment by markgoddard** [comment] 2015-01-08 11:59
The following from 2012 also points out the issue. The suggested workaround is to kill the threads. This does not seem to be a clean solution to me.

https://gist.github.com/teh/1126302

**Comment by temoto** [comment] 2015-02-09 22:14
Hello. Thanks for pointing this out. Indeed, select is a very good design approach here. Maybe we'll do a simple `is_alive` boolean for efficiency since there can't be any parallelism to corrupt memory anyway.

**Comment by roba91** [comment] 2017-04-27 05:18
I came across this issue as it's also the cause of https://github.com/miguelgrinberg/Flask-SocketIO/issues/199

**Comment by temoto** [comment] 2017-04-28 21:01
Please test this patch.

`pip install https://github.com/eventlet/eventlet/archive/81b47c20daaaf79e1a662491970dcc7f213ea117.zip`

**Comment by temoto** [comment] 2017-04-29 11:48
Scratch that, please test this patch instead.

`pip install https://github.com/eventlet/eventlet/archive/84cc764afdf83370ec236163e9ab05f0dad9c6e7.zip`

**Comment by roba91** [comment] 2017-05-03 07:44
@temoto The patch seems to work.

**Comment by temoto** [comment] 2017-05-03 09:47
@roba91 thank you.

The fix is merged in master 7f53465578543156e7251e243c0636e087a8445f

**Closed by temoto** 2017-05-03 09:47 UTC
Labels: importance-enhancement, need-feedback
