### ISSUE TITLE
0.33.0: test suite uses `nose`

### ISSUE THREAD

**Issue by kloczek** [eventlet/eventlet#744] opened 2022-01-10 16:19 UTC
`nose` module is o longer maintained and should not be used with python 3.x https://nose.readthedocs.io/en/latest/
On migration from `nose` to pytest may be useful https://github.com/schollii/nose2pytest/

**Comment by temoto** [comment] 2022-01-10 17:11
Duplicate of https://github.com/eventlet/eventlet/issues/638

TL;DR:
- nose works, there are no problems with it to maintain
- eventlet only installs nose in separate tox virtualenv, so anything related to OS or global packages is not applicable here
- we all agree to switch to pytest, but it is not done yet

**Closed by temoto** 2022-01-10 17:11 UTC

**Comment by kloczek** [comment] 2022-01-10 18:53
If you will look closer on nose and pytest it is easy to spot that it not the same league.
This is why `nose` development has been abandoned.
Main power of the pytest comes from additional extensions which may alter testing by only install extension without touching tested code or test suite.

**Comment by temoto** [comment] 2022-01-10 20:48
Thank you, Tomasz. I did look closer at pytest sometime around 2012. It has all required features: conditional skip, timeout, order shuffle, parallelization. Order shuffle is surprisingly worse than in nose (not global), but no big deal.

We can talk leagues, abandonment and other emotional things in (possibly virtual) beer situation. This project tries to use very limited active contributor time into making a good network library. It would be so awesome to say we fixed all important issues, so that uncool test runner is the next target, but we're not there yet.

> alter testing by only install extension

There's a similar issue in this project: https://github.com/eventlet/eventlet/issues/701

FWIW, my personal opinion, such invasive behavior would be a bug. Luckily, exact test configuration, including runner version, plugins and command line is locked as code in tox.ini, so that would not be a problem.

**Comment by kloczek** [comment] 2022-01-10 22:54
> FWIW, my personal opinion, such invasive behavior would be a bug. Luckily, exact test configuration, including runner version, plugins and command line is locked as code in tox.ini, so that would not be a problem.

As with everything is is easy to find good and bad cases :)
Nevertheless as I wrote pytest power comes from pluggability which allows for example add coverity or indentation/formatting checks and all without changing anything in tested code or some configuration files. All what you need to do is just install exact extension :)

Working on Linux/Solaris distribution I have at he moment +750 modules as packages. In that population I'm trying to use pytest as much as possible.
```console
[tkloczko@ss-desktop SPECS]$ grep %pytest python-* | wc -l; ls -1 python-* | wc -l
673
765
```
With as you see almost 90% of all packages tested using pytest I want to create kind of public ranking all those module which are passing for example tests with `pytest-randomly`, `pytest-cov`, or create performance metrics using `pytest-benchmark` (additionally have some data for regression tests when for example new python version will be released.
With pytest I would be able to do that without touching even single line of build procedures described in rpm spec files and only by altering build env (adding or removing some pytest extensions).
For me it is kind of platform which may present more actual data about quality of the code exact module.
I'm 100% sure that you would you would be able to find on https://docs.pytest.org/en/latest/reference/plugin_list.html which would be able to make your work easier/more productive so what I'm doing it is nothing more than just gentle suggestion to switch to something which IMO opens new tooling doors :)
Only this and nothing more :P
