### ISSUE TITLE
 error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry

### ISSUE THREAD

**Issue by remimin** [eventlet/eventlet#114] opened 2014-07-31 07:23 UTC
python 2.6.6
eventlet 0.13 version
```
 self._socket = eventlet.wrap_ssl(self._socket, **ssl_kwargs) 
File "/usr/lib/python2.6/site-packages/eventlet/wsgi.py", line 399, in handle_one_response
    write(''.join(towrite))
  File "/usr/lib/python2.6/site-packages/eventlet/wsgi.py", line 349, in write
    _writelines(towrite)
  File "/usr/lib64/python2.6/socket.py", line 334, in writelines
    self.flush()
  File "/usr/lib64/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
  File "/usr/lib/python2.6/site-packages/eventlet/green/ssl.py", line 131, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.6/site-packages/eventlet/green/ssl.py", line 107, in send
    super(GreenSSLSocket, self).send, data, flags)
  File "/usr/lib/python2.6/site-packages/eventlet/green/ssl.py", line 77, in _call_trampolining
    return func(*a, **kw)
  File "/usr/lib64/python2.6/ssl.py", line 174, in send
    v = self._sslobj.write(data)
SSLError: [Errno 1] _ssl.c:1276: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry
```

**Comment by liorn** [comment] 2015-01-04 14:02
To reproduce:
1. Create 10 SSL sockets
2. eventlet.spawn 10 functions which continuously send large amount of data to that socket: `s.send(large_string)`, where `len(large_string)` is 1MB for example

Reproduces easily on my machine.

**Comment by liorn** [comment] 2015-01-04 14:21
I found the bug. Will submit a pull request soon

**Comment by jstasiak** [comment] 2015-02-08 02:40
@remimin @liorn This is an interesting issue, I spent a chunk of the day trying to reproduce the issue and debugging Python binary to make sure the only piece of code that can cause that error is being executed and it was, but the conditions inside weren't being met.

My system: OS X 10.9.5, OpenSSL 0.9.9 (I think it's 0.9.8y but I don't see the version being specified formally anywhere), Python 2.7.9 and 2.6.8, eventlet 0.15.1 and 0.16.1.

I wrote a code doing what you described (creating lots of SSL sockets and sending a lot of data through them, no success there (for the record https://github.com/openssl/openssl/blob/OpenSSL_0_9_8y/ssl/s3_pkt.c#L744 piece of code actually generating that error is the piece of code that'd generate the error).

@remimin What OpenSSL version are you using?
@liorn Similarlu, what Python and OpenSSL version are you using and what operating system?

Can you provide a runnable code that reproduces the issue?

**Comment by liorn** [comment] 2015-02-08 09:37
I'm running Windows 8.1 with Python 2.6.4.

**Comment by jstasiak** [comment] 2015-02-09 23:51
Actually it's not in master yet, I was on the fence as I could not reproduce it. On the other hand if it fixes things for you it seems worth merging. @temoto: opinion?

**Comment by temoto** [comment] 2015-02-10 00:57
I actually quite like the patch if only for less copying. Merged.

**Closed by temoto** 2015-02-10 00:57 UTC
